// <auto-generated />
using System;
using Friendout.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Friendout.Domain.Migrations
{
    [DbContext(typeof(FriendoutDbContext))]
    [Migration("20260809160646_AddActivityShareToken")]
    partial class AddActivityShareToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Friendout.Domain.Models.AccessRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Status");

                    b.ToTable("access_requests");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdToken")
                        .HasColumnType("text")
                        .HasColumnName("id_token");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("provider_account_id");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("scope");

                    b.Property<string>("SessionState")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("session_state");

                    b.Property<string>("TokenType")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("token_type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderAccountId")
                        .IsUnique();

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("achievements");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("end_at");

                    b.Property<double?>("EstimatedPrice")
                        .HasColumnType("double")
                        .HasColumnName("estimated_price");

                    b.Property<string>("ImageId")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("image_id");

                    b.Property<string>("LocalisationId")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("localisation_id");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("reminder_sent_at");

                    b.Property<string>("ShareToken")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("share_token");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("start_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ImageId");

                    b.HasIndex("LocalisationId");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasFilter("`share_token` IS NOT NULL");

                    b.HasIndex("StartAt");

                    b.HasIndex("StartAt", "ReminderSentAt");

                    b.ToTable("activities");
                });

            modelBuilder.Entity("Friendout.Domain.Models.ActivityComment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("activity_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("activity_comments");
                });

            modelBuilder.Entity("Friendout.Domain.Models.ActivityEquipment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("activity_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("equipment_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<bool>("Required")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("required");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ActivityId", "EquipmentId")
                        .IsUnique();

                    b.ToTable("activity_equipments");
                });

            modelBuilder.Entity("Friendout.Domain.Models.AllowedEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("allowed_emails");
                });

            modelBuilder.Entity("Friendout.Domain.Models.AllowedGuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("allowed_guilds");
                });

            modelBuilder.Entity("Friendout.Domain.Models.AppLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT")
                        .HasColumnName("exception");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Level");

                    b.ToTable("app_logs");
                });

            modelBuilder.Entity("Friendout.Domain.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_settings");

                    b.HasData(
                        new
                        {
                            Key = "discord_restricted",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "google_restricted",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        });
                });

            modelBuilder.Entity("Friendout.Domain.Models.Equipment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("equipment");
                });

            modelBuilder.Entity("Friendout.Domain.Models.EquipmentList", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("equipment_lists");
                });

            modelBuilder.Entity("Friendout.Domain.Models.EquipmentListItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("EquipmentListId")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("equipment_list_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentListId");

                    b.ToTable("equipment_list_items");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasColumnType("text")
                        .HasColumnName("alt_text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<string>("MimeType")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("name");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("images");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Localisation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("DisplayName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("MapLink")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("map_link");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("VirtualUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("virtual_url");

                    b.HasKey("Id");

                    b.ToTable("localisations");
                });

            modelBuilder.Entity("Friendout.Domain.Models.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_revoked");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.HasKey("Token");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("session_token");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("Friendout.Domain.Models.SubActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("activity_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("end_time");

                    b.Property<string>("LocalisationId")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("localisation_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("name");

                    b.Property<double?>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("LocalisationId");

                    b.ToTable("sub_activities");
                });

            modelBuilder.Entity("Friendout.Domain.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("email_verified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("name");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int")
                        .HasColumnName("achievement_id");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("unlocked_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("user_achievements");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserEquipment", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.Property<string>("EquipmentId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("equipment_id");

                    b.Property<string>("ActivityId")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("activity_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("UserId", "EquipmentId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("user_equipment");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("user_notifications");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserNotificationPreferences", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_enabled");

                    b.Property<bool>("InAppEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("in_app_enabled");

                    b.Property<string>("NotificationSound")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("notification_sound");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_notification_preferences");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserParticipation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("activity_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("SubActivityId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("sub_activity_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SubActivityId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ActivityId", "SubActivityId")
                        .IsUnique();

                    b.ToTable("user_participations");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserPreferences", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("locale");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_preferences");
                });

            modelBuilder.Entity("Friendout.Domain.Models.VerificationToken", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("identifier");

                    b.HasKey("Token");

                    b.HasIndex("Expires");

                    b.HasIndex("Identifier");

                    b.ToTable("verification_tokens");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Account", b =>
                {
                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Activity", b =>
                {
                    b.HasOne("Friendout.Domain.Models.User", "Creator")
                        .WithMany("CreatedActivities")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Friendout.Domain.Models.Localisation", "Localisation")
                        .WithMany("Activities")
                        .HasForeignKey("LocalisationId");

                    b.Navigation("Creator");

                    b.Navigation("Image");

                    b.Navigation("Localisation");
                });

            modelBuilder.Entity("Friendout.Domain.Models.ActivityComment", b =>
                {
                    b.HasOne("Friendout.Domain.Models.Activity", "Activity")
                        .WithMany("Comments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.ActivityEquipment", b =>
                {
                    b.HasOne("Friendout.Domain.Models.Activity", "Activity")
                        .WithMany("ActivityEquipments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.Equipment", "Equipment")
                        .WithMany("ActivityEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Friendout.Domain.Models.EquipmentList", b =>
                {
                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("EquipmentLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.EquipmentListItem", b =>
                {
                    b.HasOne("Friendout.Domain.Models.EquipmentList", "EquipmentList")
                        .WithMany("Items")
                        .HasForeignKey("EquipmentListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentList");
                });

            modelBuilder.Entity("Friendout.Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Session", b =>
                {
                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.SubActivity", b =>
                {
                    b.HasOne("Friendout.Domain.Models.Activity", "Activity")
                        .WithMany("SubActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.Localisation", "Localisation")
                        .WithMany()
                        .HasForeignKey("LocalisationId");

                    b.Navigation("Activity");

                    b.Navigation("Localisation");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserAchievement", b =>
                {
                    b.HasOne("Friendout.Domain.Models.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserEquipment", b =>
                {
                    b.HasOne("Friendout.Domain.Models.Activity", "Activity")
                        .WithMany("UserEquipments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.Equipment", "Equipment")
                        .WithMany("UserEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("UserEquipments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Equipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserNotification", b =>
                {
                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserNotificationPreferences", b =>
                {
                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithOne("NotificationPreferences")
                        .HasForeignKey("Friendout.Domain.Models.UserNotificationPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserParticipation", b =>
                {
                    b.HasOne("Friendout.Domain.Models.Activity", "Activity")
                        .WithMany("UserParticipations")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.SubActivity", "SubActivity")
                        .WithMany("UserParticipations")
                        .HasForeignKey("SubActivityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("UserParticipation")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("SubActivity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserPreferences", b =>
                {
                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("Friendout.Domain.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Activity", b =>
                {
                    b.Navigation("ActivityEquipments");

                    b.Navigation("Comments");

                    b.Navigation("SubActivities");

                    b.Navigation("UserEquipments");

                    b.Navigation("UserParticipations");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Equipment", b =>
                {
                    b.Navigation("ActivityEquipments");

                    b.Navigation("UserEquipments");
                });

            modelBuilder.Entity("Friendout.Domain.Models.EquipmentList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Localisation", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Friendout.Domain.Models.SubActivity", b =>
                {
                    b.Navigation("UserParticipations");
                });

            modelBuilder.Entity("Friendout.Domain.Models.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Comments");

                    b.Navigation("CreatedActivities");

                    b.Navigation("EquipmentLists");

                    b.Navigation("NotificationPreferences");

                    b.Navigation("Notifications");

                    b.Navigation("Preferences");

                    b.Navigation("Sessions");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserEquipments");

                    b.Navigation("UserParticipation");
                });
#pragma warning restore 612, 618
        }
    }
}
