// <auto-generated />
using System;
using Friendout.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Friendout.Domain.Migrations
{
    [DbContext(typeof(FriendoutDbContext))]
    [Migration("20260515092021_AddAppSettings")]
    partial class AddAppSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Friendout.Domain.Models.AccessRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Status");

                    b.ToTable("access_requests");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdToken")
                        .HasColumnType("text")
                        .HasColumnName("id_token");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("providerAccountId");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("scope");

                    b.Property<string>("SessionState")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("session_state");

                    b.Property<string>("TokenType")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("token_type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderAccountId")
                        .IsUnique();

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("achievement");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("createdBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("endAt");

                    b.Property<double?>("EstimatedPrice")
                        .HasColumnType("double")
                        .HasColumnName("estimatedPrice");

                    b.Property<string>("ImageId")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("imageId");

                    b.Property<string>("LocalisationId")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("localisationId");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("startAt");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ImageId");

                    b.HasIndex("LocalisationId");

                    b.HasIndex("StartAt");

                    b.ToTable("activities");
                });

            modelBuilder.Entity("Friendout.Domain.Models.ActivityComment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("activityId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("Activity_comment");
                });

            modelBuilder.Entity("Friendout.Domain.Models.ActivityEquipment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("activityId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("createdAt");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("equipmentId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<bool>("Required")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("required");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ActivityId", "EquipmentId")
                        .IsUnique();

                    b.ToTable("activity_equipment");
                });

            modelBuilder.Entity("Friendout.Domain.Models.AllowedEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("allowed_emails");
                });

            modelBuilder.Entity("Friendout.Domain.Models.AllowedGuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("allowed_guilds");
                });

            modelBuilder.Entity("Friendout.Domain.Models.AppLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT")
                        .HasColumnName("exception");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Level");

                    b.ToTable("app_logs");
                });

            modelBuilder.Entity("Friendout.Domain.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_settings");

                    b.HasData(
                        new
                        {
                            Key = "discord_restricted",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "google_restricted",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        });
                });

            modelBuilder.Entity("Friendout.Domain.Models.Equipment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("equipment");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasColumnType("text")
                        .HasColumnName("altText");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("createdBy");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<string>("MimeType")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("mimeType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("name");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("images");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Localisation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("DisplayName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("displayName");

                    b.Property<string>("MapLink")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("mapLink");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("VirtualUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("virtualUrl");

                    b.HasKey("Id");

                    b.ToTable("localisation");
                });

            modelBuilder.Entity("Friendout.Domain.Models.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(191)");

                    b.HasKey("Token");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sessionToken");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("Friendout.Domain.Models.SubActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("activityId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("endTime");

                    b.Property<string>("LocalisationId")
                        .HasColumnType("varchar(191)")
                        .HasColumnName("localisationId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("name");

                    b.Property<double?>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("startTime");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("LocalisationId");

                    b.ToTable("sub_activities");
                });

            modelBuilder.Entity("Friendout.Domain.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatarUrl");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("emailVerified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("name");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int")
                        .HasColumnName("achievementId");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("unlockedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("user_achievements");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserEquipment", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("userId");

                    b.Property<string>("EquipmentId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("equipmentId");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("varchar(191)")
                        .HasColumnName("activity_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("UserId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("UserId");

                    b.ToTable("user_equipment");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserParticipation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("activityId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdAt");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("SubActivityId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("subActivityId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SubActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("user_participation");
                });

            modelBuilder.Entity("Friendout.Domain.Models.VerificationToken", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("identifier");

                    b.HasKey("Token");

                    b.HasIndex("Expires");

                    b.HasIndex("Identifier");

                    b.ToTable("verification_tokens");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Account", b =>
                {
                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Activity", b =>
                {
                    b.HasOne("Friendout.Domain.Models.User", "Creator")
                        .WithMany("CreatedActivities")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Friendout.Domain.Models.Localisation", "Localisation")
                        .WithMany("Activities")
                        .HasForeignKey("LocalisationId");

                    b.Navigation("Creator");

                    b.Navigation("Image");

                    b.Navigation("Localisation");
                });

            modelBuilder.Entity("Friendout.Domain.Models.ActivityComment", b =>
                {
                    b.HasOne("Friendout.Domain.Models.Activity", "Activity")
                        .WithMany("Comments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.ActivityEquipment", b =>
                {
                    b.HasOne("Friendout.Domain.Models.Activity", "Activity")
                        .WithMany("ActivityEquipments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.Equipment", "Equipment")
                        .WithMany("ActivityEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Friendout.Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Session", b =>
                {
                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.SubActivity", b =>
                {
                    b.HasOne("Friendout.Domain.Models.Activity", "Activity")
                        .WithMany("SubActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.Localisation", "Localisation")
                        .WithMany()
                        .HasForeignKey("LocalisationId");

                    b.Navigation("Activity");

                    b.Navigation("Localisation");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserAchievement", b =>
                {
                    b.HasOne("Friendout.Domain.Models.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserEquipment", b =>
                {
                    b.HasOne("Friendout.Domain.Models.Equipment", "Equipment")
                        .WithMany("UserEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("UserEquipments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.UserParticipation", b =>
                {
                    b.HasOne("Friendout.Domain.Models.Activity", "Activity")
                        .WithMany("UserParticipations")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friendout.Domain.Models.SubActivity", "SubActivity")
                        .WithMany("UserParticipations")
                        .HasForeignKey("SubActivityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Friendout.Domain.Models.User", "User")
                        .WithMany("UserParticipation")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("SubActivity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Activity", b =>
                {
                    b.Navigation("ActivityEquipments");

                    b.Navigation("Comments");

                    b.Navigation("SubActivities");

                    b.Navigation("UserParticipations");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Equipment", b =>
                {
                    b.Navigation("ActivityEquipments");

                    b.Navigation("UserEquipments");
                });

            modelBuilder.Entity("Friendout.Domain.Models.Localisation", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Friendout.Domain.Models.SubActivity", b =>
                {
                    b.Navigation("UserParticipations");
                });

            modelBuilder.Entity("Friendout.Domain.Models.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Comments");

                    b.Navigation("CreatedActivities");

                    b.Navigation("Sessions");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserEquipments");

                    b.Navigation("UserParticipation");
                });
#pragma warning restore 612, 618
        }
    }
}
